/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author bhagya
 */
public class View_attendance extends javax.swing.JFrame {

        static Connection c=null;
        static String userid;
    /**
     * Creates new form View_attendance
     */
    public View_attendance() {
        initComponents();
        setSize(400, 550);
        this.setLocationRelativeTo(null);
        
    }

    View_attendance(String user) {
        initComponents();
        setSize(400, 550);
        this.setLocationRelativeTo(null);
        userid = user;
        
        Statement stmt,stm,stmts;
        try{
            Class.forName("org.postgresql.Driver");
            c=DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres","postgres","bhagyapostgres");
            stmt = c.createStatement();
            RollNo.setText(userid);
            String sql="select student_name from student where student_id = '"+userid+"';";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                String student_name = rs.getString("student_name");
                St_name.setText(student_name);
            }
            stmt.close();
        }catch(SQLException err)
        {
         System.out.println("SQL Exception");
        }catch(ClassNotFoundException e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);
        }
        
        try{
            Class.forName("org.postgresql.Driver");
            c=DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres","postgres","bhagyapostgres");
            stmt = c.createStatement();
            stmts = c.createStatement();
            String sql="select * from teacher_student where student_id = '"+userid+"'";
            ResultSet rs = stmt.executeQuery(sql);
            int row = 0;
            while(rs.next()){
                stm = c.createStatement();
                String sq = "select subject_code from teacher where teacher_id = '"+rs.getString("teacher_id")+"';";
                ResultSet r = stm.executeQuery(sq);
                while(r.next()){
                   
                    DefaultTableModel model = (DefaultTableModel) Register.getModel();
                    row=Register.getRowCount()+1;
                    model.setRowCount(row);
                    Object id = r.getString("subject_code");
                    Register.getModel().setValueAt(id, (row - 1), 0);
                    
                    String s = "select count(*) as total from attendance_register where teacher_id ='"+rs.getString("teacher_id")+"' and student_id = '"+userid+"';";
                    ResultSet rst = stmts.executeQuery(s);
                    rst.next();
                    Object total = rst.getInt("total");
                    Register.getModel().setValueAt(total, (row - 1), 1);
                    
                    String str = "select count(*) as attend from attendance_register where teacher_id ='"+rs.getString("teacher_id")+"' and student_id = '"+userid+"' and presence = true;";
                    ResultSet rest = stmts.executeQuery(str);
                    rest.next();
                    Object attend = rest.getInt("attend");
                    Register.getModel().setValueAt(attend, (row - 1), 2);
                    
                }    
                stm.close();
            }      
        stmt.close();
        }catch(SQLException err)
        {
         System.out.println("SQL Exception");
        }catch(ClassNotFoundException e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Register = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        RollNo = new javax.swing.JLabel();
        St_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Total", "Attended"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Register.setRowHeight(30);
        jScrollPane1.setViewportView(Register);

        jLabel1.setFont(new java.awt.Font("Purisa", 3, 30)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icon-easyattendance.png"))); // NOI18N
        jLabel1.setText("MyAttendance");

        RollNo.setFont(new java.awt.Font("Purisa", 3, 24)); // NOI18N

        St_name.setFont(new java.awt.Font("Purisa", 3, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RollNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(St_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(St_name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Student t;
        t=new Student(userid);
        t.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Register;
    public static javax.swing.JLabel RollNo;
    public static javax.swing.JLabel St_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
